import fs from 'fs';
import path from 'path';

export const products = [
    // ══════════════════════════════════════════════════════════════════════════════
    // 1. อาหาร (cat1) - 16 รายการ
    // ══════════════════════════════════════════════════════════════════════════════
    {
        id: 'p1',
        sku: 'XM-FOOD-0001',
        name: 'มาม่า บะหมี่กึ่งสำเร็จรูป รสต้มยำกุ้ง 55g',
        brand: 'มาม่า',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'บะหมี่กึ่งสำเร็จรูปรสต้มยำกุ้งยอดนิยม ซุปเข้มข้นถึงเครื่องต้มยำแท้ เส้นเหนียวนุ่ม อร่อยทุกคำ',
        price: 7,
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
        stock: 120,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p2',
        sku: 'XM-FOOD-0002',
        name: 'มาม่า บะหมี่กึ่งสำเร็จรูป รสหมูสับ 55g',
        brand: 'มาม่า',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'รสชาติคลาสสิกที่ทุกคนคุ้นเคย น้ำซุปหมูสับหอมกรุ่น กลมกล่อม เส้นนุ่มละมุนลิ้น',
        price: 7,
        image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&q=80',
        stock: 100,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p3',
        sku: 'XM-FOOD-0003',
        name: 'ข้าวหอมมะลิ 100% ตราหงษ์ทอง 5 กก.',
        brand: 'หงษ์ทอง',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ข้าวหอมมะลิแท้คัดพิเศษ เมล็ดเรียวยาว หุงขึ้นหม้อ นุ่มเหนียวกำลังดี กลิ่นหอมธรรมชาติ',
        price: 215,
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80',
        stock: 35,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p4',
        sku: 'XM-FOOD-0004',
        name: 'ไข่ไก่สด เบอร์ 2 แพ็ค 10 ฟอง',
        brand: 'ซีพี',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ไข่ไก่สดคัดคุณภาพจากฟาร์มมาตรฐาน สะอาด ปลอดภัย อุดมด้วยโปรตีนและสารอาหารจำเป็น',
        price: 49,
        image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&q=80',
        stock: 45,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p5',
        sku: 'XM-FOOD-0005',
        name: 'น้ำปลาแท้ ตราทิพรส 700 มล.',
        brand: 'ทิพรส',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'น้ำปลาแท้คุณภาพอันดับหนึ่ง หมักจากปลากะตักสดตามธรรมชาติ กลิ่นหอม รสชาติเค็มกลมกล่อม',
        price: 32,
        image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&q=80',
        stock: 60,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p22',
        sku: 'XM-FOOD-0006',
        name: 'น้ำจิ้มสุกี้ กวางตุ้ง พันท้ายนรสิงห์ 330g',
        brand: 'พันท้ายนรสิงห์',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'น้ำจิ้มสุกี้สูตรกวางตุ้งยอดนิยม รสชาติเข้มข้น หอมกลิ่นงาขาวคั่ว ครบรสเปรี้ยว หวาน เค็ม เผ็ด',
        price: 45,
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80',
        stock: 40,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p23',
        sku: 'XM-FOOD-0007',
        name: 'น้ำตาลทรายขาวบริสุทธิ์ มิตรผล 1 กก.',
        brand: 'มิตรผล',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'น้ำตาลทรายขาวบริสุทธิ์จากอ้อยธรรมชาติ เกล็ดขาวสะอาด ละลายง่าย เหมาะสำหรับทำอาหารและขนม',
        price: 28,
        image: 'https://images.unsplash.com/photo-1622484212850-cab596d634db?w=600&q=80',
        stock: 80,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-008',
        sku: 'XM-FOOD-0008',
        name: 'ปลากระป๋องในซอสมะเขือเทศ สามแม่ครัว 155g',
        brand: 'สามแม่ครัว',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ปลาซาร์ดีนเนื้อแน่นในซอสมะเขือเทศเข้มข้น รสชาติกลมกล่อม สะอาด ผ่านการฆ่าเชื้อด้วยระบบสเตอริไลซ์',
        price: 19,
        image: 'https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=600&q=80',
        stock: 90,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-009',
        sku: 'XM-FOOD-0009',
        name: 'น้ำมันถั่วเหลือง องุ่น 1 ลิตร',
        brand: 'องุ่น',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'น้ำมันพืชสกัดจากถั่วเหลือง 100% ไม่เป็นไข ไม่มีคอเลสเตอรอล เหมาะสำหรับผัดและทอดอาหารทุกชนิด',
        price: 55,
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
        stock: 75,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-010',
        sku: 'XM-FOOD-0010',
        name: 'ซอสหอยนางรม ตราแม่ครัว 600 มล.',
        brand: 'แม่ครัว',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ซอสหอยนางรมแท้สูตรดั้งเดิม ผลิตจากหอยนางรมสด คัดสรรอย่างดี รสชาติกลมกล่อมหอมอร่อย',
        price: 42,
        image: 'https://images.unsplash.com/photo-1514944298352-78d1844b360b?w=600&q=80',
        stock: 50,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-011',
        sku: 'XM-FOOD-0011',
        name: 'คนอร์ คัพโจ๊ก รสหมู 35g',
        brand: 'คนอร์',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'โจ๊กกึ่งสำเร็จรูปรสหมู ทำจากข้าวหอมมะลิแท้ มีวิตามินบี 1, 3, 6 สูง อิ่มอร่อยง่ายๆ ใน 2 นาที',
        price: 18,
        image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&q=80',
        stock: 85,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-012',
        sku: 'XM-FOOD-0012',
        name: 'ซอสพริก ศรีราชาพานิช เผ็ดกลาง 230g',
        brand: 'ศรีราชาพานิช',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ซอสพริกศรีราชาสูตรดั้งเดิม รสชาติเผ็ดกำลังดี เปรี้ยวหวานกลมกล่อม ไม่ใส่วัตถุกันเสีย',
        price: 35,
        image: 'https://images.unsplash.com/photo-1589135233689-d49fa2a52b5b?w=600&q=80',
        stock: 45,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-013',
        sku: 'XM-FOOD-0013',
        name: 'ซีอิ๊วขาวเห็ดหอม เด็กสมบูรณ์ 600 มล.',
        brand: 'เด็กสมบูรณ์',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'ซีอิ๊วขาวสูตรพิเศษผสมสารสกัดเห็ดหอมธรรมชาติ ให้กลิ่นหอมชวนรับประทาน เพิ่มรสชาติให้อาหารจานโปรด',
        price: 52,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
        stock: 40,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-014',
        sku: 'XM-FOOD-0014',
        name: 'วุ้นเส้นถั่วเขียว ตราต้นสน 100g',
        brand: 'ต้นสน',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'วุ้นเส้นผลิตจากถั่วเขียวชั้นดี เส้นเหนียวนุ่ม ไม่อืด ไม่เละ เหมาะสำหรับยำ ผัด ต้มจืด และชาบู',
        price: 16,
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
        stock: 65,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-015',
        sku: 'XM-FOOD-0015',
        name: 'ทูน่าสเต็กในน้ำแร่ ซีเล็คทูน่า 165g',
        brand: 'ซีเล็ค',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'เนื้อปลาทูน่าแท้ชิ้นใหญ่ แคลอรีต่ำ อุดมด้วยโปรตีนและโอเมก้า 3 ไม่มีวัตถุกันเสีย',
        price: 48,
        image: 'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=600&q=80',
        stock: 30,
        isUnlimitedStock: false,
        status: 'AVAILABLE'
    },
    {
        id: 'p-food-016',
        sku: 'XM-FOOD-0016',
        name: 'เกลือบริสุทธิ์เสริมไอโอดีน ปรุงทิพย์ 500g',
        brand: 'ปรุงทิพย์',
        category: 'อาหาร',
        categoryId: 'cat1',
        description: 'เกลือแกงบริสุทธิ์ 99.9% ขาวสะอาด เมล็ดละเอียด ไม่ชื้นง่าย เสริมไอโอดีนป้องกันโรคคอพอก',
        price: 14,
        image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=600&q=80',
        stock: 90,
        isUnlimitedStock: true,
        status: 'AVAILABLE'
    }
];

console.log('Sample product definitions ready');
